development:
  adapter: postgresql
  encoding: unicode
  database: sample_dev
  host: localhost
  pool: 5
  username: markrichman
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sample_test
  host: localhost
  pool: 5
  username: markrichman
  password:
